[package]
name = "nano-vectordb-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.21"
uuid = { version = "1.6", features = ["v4", "serde"] }
itertools = "0.12"
serde_json = "1.0.138"
rayon = "1.9"
