name: code checks
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/code_checks.yml
      - '**.rs'
      - Cargo.lock
      - Cargo.toml
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/code_checks.yml
      - '**.rs'
      - Cargo.lock
      - Cargo.toml

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  check:
    name: Basic Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Check formatting
        run: cargo fmt -- --check
      
      - name: Check build
        run: cargo check --all-features

  test:
    name: Coverage Tests
    runs-on: ubuntu-latest
    needs: check
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2024-03-01
          components: llvm-tools-preview
      
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Run Tarpaulin
        run: |
          cargo tarpaulin --verbose \
            --engine llvm \
            --all-features \
            --workspace \
            --timeout 120 \
            --out xml \
            --exclude-files "src/bin/*" \
            --exclude-files "pulp/**" \
            --skip-clean \
            --output-dir target/tarpaulin/
      
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: amrit110/nano-vectordb-rs
          files: target/tarpaulin/cobertura.xml
          verbose: true
